import { test, expect } from '@playwright/test';
import { OpenurlPage } from '../pages/openurl-page';
import { TboxWaitPage } from '../pages/tbox-wait-page';
import { WebshopTopMenuPage } from '../pages/webshop-top-menu-page';
import { WebshopLogInPagePage } from '../pages/webshop-log-in-page-page';
import { TboxSetBufferPage } from '../pages/tbox-set-buffer-page';
import { WebshopProductsChoiceTabPage } from '../pages/webshop-products-choice-tab-page';
import { WebshopApparelShoesProductSelectionPage } from '../pages/webshop-apparel-shoes-product-selection-page';
import { WebshopBlueJeansPage } from '../pages/webshop-blue-jeans-page';
import { WebshopShoppingCartPage } from '../pages/webshop-shopping-cart-page';
import { WebshopBillingAddressPage } from '../pages/webshop-billing-address-page';
import { WebshopShippingAddressPage } from '../pages/webshop-shipping-address-page';
import { WebshopShippingMethodPage } from '../pages/webshop-shipping-method-page';
import { WebshopPaymentMethodsPage } from '../pages/webshop-payment-methods-page';
import { WebshopPaymentInformationCreditCardPage } from '../pages/webshop-payment-information-credit-card-page';
import { WebshopConfirmOrderPage } from '../pages/webshop-confirm-order-page';
import { WebshopOrderSuccessfulPage } from '../pages/webshop-order-successful-page';
import { WebshopMyAccountNavigationPage } from '../pages/webshop-my-account-navigation-page';
import { WebshopOrderDetailsPage } from '../pages/webshop-order-details-page';
import { ClosebrowserPage } from '../pages/closebrowser-page';
import { faker } from '@faker-js/faker';
import { format, addMonths } from 'date-fns';

test.describe('DemoWebShop_Order_Creation|Buiseness Parameters|RTB', () => {
  let openurlPage: OpenurlPage;
  let tboxWaitPage: TboxWaitPage;
  let webshopTopMenuPage: WebshopTopMenuPage;
  let webshopLogInPagePage: WebshopLogInPagePage;
  let tboxSetBufferPage: TboxSetBufferPage;
  let webshopProductsChoiceTabPage: WebshopProductsChoiceTabPage;
  let webshopApparelShoesProductSelectionPage: WebshopApparelShoesProductSelectionPage;
  let webshopBlueJeansPage: WebshopBlueJeansPage;
  let webshopShoppingCartPage: WebshopShoppingCartPage;
  let webshopBillingAddressPage: WebshopBillingAddressPage;
  let webshopShippingAddressPage: WebshopShippingAddressPage;
  let webshopShippingMethodPage: WebshopShippingMethodPage;
  let webshopPaymentMethodsPage: WebshopPaymentMethodsPage;
  let webshopPaymentInformationCreditCardPage: WebshopPaymentInformationCreditCardPage;
  let webshopConfirmOrderPage: WebshopConfirmOrderPage;
  let webshopOrderSuccessfulPage: WebshopOrderSuccessfulPage;
  let webshopMyAccountNavigationPage: WebshopMyAccountNavigationPage;
  let webshopOrderDetailsPage: WebshopOrderDetailsPage;
  let closebrowserPage: ClosebrowserPage;

  test.beforeEach(async ({ page }) => {
    openurlPage = new OpenurlPage(page);
    tboxWaitPage = new TboxWaitPage(page);
    webshopTopMenuPage = new WebshopTopMenuPage(page);
    webshopLogInPagePage = new WebshopLogInPagePage(page);
    tboxSetBufferPage = new TboxSetBufferPage(page);
    webshopProductsChoiceTabPage = new WebshopProductsChoiceTabPage(page);
    webshopApparelShoesProductSelectionPage = new WebshopApparelShoesProductSelectionPage(page);
    webshopBlueJeansPage = new WebshopBlueJeansPage(page);
    webshopShoppingCartPage = new WebshopShoppingCartPage(page);
    webshopBillingAddressPage = new WebshopBillingAddressPage(page);
    webshopShippingAddressPage = new WebshopShippingAddressPage(page);
    webshopShippingMethodPage = new WebshopShippingMethodPage(page);
    webshopPaymentMethodsPage = new WebshopPaymentMethodsPage(page);
    webshopPaymentInformationCreditCardPage = new WebshopPaymentInformationCreditCardPage(page);
    webshopConfirmOrderPage = new WebshopConfirmOrderPage(page);
    webshopOrderSuccessfulPage = new WebshopOrderSuccessfulPage(page);
    webshopMyAccountNavigationPage = new WebshopMyAccountNavigationPage(page);
    webshopOrderDetailsPage = new WebshopOrderDetailsPage(page);
    closebrowserPage = new ClosebrowserPage(page);

    await page.goto('https://demowebshop.tricentis.com/');
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(15000);
    await page.waitForLoadState('networkidle');
    await expect(webshopTopMenuPage.logIn).toBeVisible();
    await webshopTopMenuPage.logIn.click();
    await page.waitForLoadState('networkidle');
    await webshopLogInPagePage.email.fill('sr.Tester123@gmail.com');
    await webshopLogInPagePage.password.fill('Tester123');
    await webshopLogInPagePage.logIn.click();
  });

  test('complete order creation with discount and verify order details', async ({ page }) => {
    let quantityno: string;
    let price: string;
    let orderNumber: string;
    let capturedOrderDetails: string;

    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(15000);
    await page.waitForLoadState('networkidle');
    quantityno = await tboxSetBufferPage.quantityno.textContent() ?? '';
    await page.waitForLoadState('networkidle');
    await webshopProductsChoiceTabPage.selectProductName.fill('APPAREL & SHOES');
    await page.waitForLoadState('networkidle');
    await webshopApparelShoesProductSelectionPage.blueJeans.click();
    await page.waitForLoadState('networkidle');
    price = await webshopBlueJeansPage.price.textContent() ?? '';
    await webshopBlueJeansPage.quantity.fill('23');
    await webshopBlueJeansPage.addToCart.click();
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(10000);
    await page.waitForLoadState('networkidle');
    await page.waitForLoadState('networkidle');
    await webshopTopMenuPage.shoppingCart.click();
    await page.waitForLoadState('networkidle');
    await webshopShoppingCartPage.enterDiscountCode.fill(process.env.DISCOUNTNAME ?? 'AutomationDiscount2');
    await webshopShoppingCartPage.applyCoupon.click();
    await expect(webshopShoppingCartPage.giftCardCouponCode).toBeVisible();
    await webshopShoppingCartPage.termsOfService.check();
    await webshopShoppingCartPage.checkout.click();
    await page.waitForLoadState('networkidle');
    await webshopBillingAddressPage.continue.click();
    await page.waitForLoadState('networkidle');
    await webshopShippingAddressPage.continue.click();
    await page.waitForLoadState('networkidle');
    await webshopShippingMethodPage.shippingMethods.fill('Ground');
    await webshopShippingMethodPage.continue.click();
    await page.waitForLoadState('networkidle');
    await webshopPaymentMethodsPage.paymentMethods.fill('Credit Card');
    await webshopPaymentMethodsPage.continue.click();
    await page.waitForLoadState('networkidle');
    await webshopPaymentInformationCreditCardPage.selectCreditCard.selectOption('Visa');
    await webshopPaymentInformationCreditCardPage.cardholderName.fill(faker.string.alpha(10));
    await webshopPaymentInformationCreditCardPage.cardNumber.fill('4485564059489345');
    await webshopPaymentInformationCreditCardPage.expirationDateMonth.selectOption(format(addMonths(new Date(), 4), 'MM'));
    await webshopPaymentInformationCreditCardPage.expirationDateYear.selectOption(format(addMonths(new Date(), 0), 'yyyy'));
    await webshopPaymentInformationCreditCardPage.cardCode.fill(String(faker.number.int({ min: 100, max: 999 })));
    await webshopPaymentInformationCreditCardPage.continue.click();
    await page.waitForLoadState('networkidle');
    await webshopConfirmOrderPage.cartTotal.fill('');
    await webshopConfirmOrderPage.confirm.click();
    await page.waitForLoadState('networkidle');
    await expect(webshopOrderSuccessfulPage.messageOrderSuccessful).toBeVisible();
    orderNumber = await webshopOrderSuccessfulPage.orderNumber.textContent() ?? '';
    await page.waitForLoadState('networkidle');
    await webshopTopMenuPage.myAccount.click();
    await page.waitForLoadState('networkidle');
    await webshopMyAccountNavigationPage.myAccountMenu.fill('');
    await page.waitForLoadState('networkidle');
    capturedOrderDetails = await webshopOrderDetailsPage['1'].textContent() ?? '';
  });

  test.afterEach(async ({ page }) => {
    await page.waitForLoadState('networkidle');
    await webshopTopMenuPage.logOut.click();
    await expect(webshopTopMenuPage.logIn).toBeVisible();
    await page.waitForLoadState('networkidle');
    await closebrowserPage.title.fill('Demo*');
  });
});